# Generated by Django 6.0.1 on 2026-01-20 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='is_owned',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
