# Generated by Django 6.0.1 on 2026-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_is_owned_remove_pokemon_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
